### ISSUE TITLE
Sparse matrix handling in the CalJac function

### ISSUE THREAD

**Issue by tony-zhelonkin** [Ying-Lab/scIBD#4]
Hello, 

I\`ve read with interest your paper on scATACseq doublet detection. I\`m giving your tool a try for my scATACseq dataset. I`m working with my scATACseq dataset in the Seurat/Signac workflow. So I made a Python script to run scIBD from inside R environment. 

**The problem** I encountered is `NotImplementedError: subtracting a sparse array from a nonzero scalar is not supported` when running scIBD.

**My plan was the following:** 
1. Convert Seurat to Anndata
2. Call the `scibd` from inside R via reticulate 
3. Extract the predictions and pull them back into my Seurat object 

So for this I`ve set up: 
- a script to run scIDB from inside R, called `run_scibd.py`.
- a script to extract prediction results from scIDB output to csv, called `convert_scibd_results.py`
- R code to execute the whole process from inside R terminal 

Here\`s the Python `run_scibd.py` script:

```python
import scibd as si
import anndata as ad
import argparse
import numpy as np
import scipy.sparse as sp

def run_doublet_detection(input_path, output_path):
    print("Reading input file...")
    adata = ad.read_h5ad(input_path)
    
    print(f"Input matrix shape: {adata.X.shape}")
    print(f"Matrix type: {type(adata.X)}")
    
    print("Converting to dense matrix...")
    if sp.issparse(adata.X):
        adata.X = adata.X.toarray()
        # Ensure the matrix is binary
        adata.X = (adata.X > 0).astype(np.float32)
    
    print("Matrix converted to dense format")
    print(f"New matrix type: {type(adata.X)}")
    print(f"Matrix values range: {adata.X.min()} - {adata.X.max()}")
    
    print("Initializing KNNIter...")
    KNNITER = si.KNNIter(
        adata,
        exprate=0.08
    )
    
    print("Running IterCall...")
    result = KNNITER.IterCall()
    
    print("Saving results...")
    result.write_h5ad(output_path)
    print("Done!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", help="Input h5ad file path")
    parser.add_argument("--output", help="Output h5ad file path")
    args = parser.parse_args()
    run_doublet_detection(args.input, args.output)
```

Here`s the Python conversion script to extract predictions results in csv. 
```python
# convert_scibd_results.py
import anndata as ad
import pandas as pd
import sys

def convert_scibd_to_csv(input_h5ad, output_csv):
    # Read AnnData
    adata = ad.read_h5ad(input_h5ad)
    
    # Extract doublet scores
    results = pd.DataFrame({
        'cell_id': adata.obs.index,
        'PredDBL': adata.obs['PredDBL'],
        'DBLscore': adata.obs['DBLscore']
    })
    
    # Save as CSV
    results.to_csv(output_csv)

if __name__ == "__main__":
    convert_scibd_to_csv(sys.argv[1], sys.argv[2])
```

I call this script for my dataset from inside the R terminal using this code:
```r
library(reticulate)

# Extract one sample
test_sample <- subset(dt_1634_atacseq_raw, subset = orig.ident == "WT")

# Save and convert to anndata
SaveH5Seurat(test_sample, filename = "test_sample.h5seurat")
Convert("test_sample.h5seurat", dest = "h5ad")

# Run Python script on test sample
system2(
    "python",
    args = c(
        "scripts/Python_scripts/run_scibd.py",
        "--input=test_sample.h5ad",
        "--output=test_sample_doublets.h5ad"
    ),
    env = c("PYTHONMEM_MAX_ALLOC=50G")
)

# Run conversion
system2(
    "python",
    args = c(
        "scripts/Python_scripts/convert_scibd_results.py",
        "test_sample_doublets.h5ad",
        "doublet_scores.csv"
    )
)

# Read results into R
doublet_scores <- read.csv("doublet_scores.csv", row.names=1)

# Transfer scores 
test_sample$scIBD_prediction <- doublet_scores$PredDBL[match(colnames(test_sample), doublet_scores$cell_id)]
test_sample$scIBD_score <- doublet_scores$DBLscore[match(colnames(test_sample), doublet_scores$cell_id)]
```

My `test_sample` is 
```R
An object of class Seurat 
215955 features across 8454 samples within 1 assay 
Active assay: peaks (215955 features, 0 variable features)
 2 layers present: counts, data
```

And so when I run scIBD from inside R using this code
```python
system2(
    "python",
    args = c(
        "scripts/Python_scripts/run_scibd.py",
        "--input=test_sample.h5ad",
        "--output=test_sample_doublets.h5ad"
    ),
    env = c("PYTHONMEM_MAX_ALLOC=50G")
)
```

I get the message 

> Reading input file...
> Input matrix shape: (8454, 215955)
> Matrix type: <class 'scipy.sparse._csr.csr_matrix'>
> Converting to dense matrix...
> Matrix converted to dense format
> New matrix type: <class 'numpy.ndarray'>
> Initializing KNNIter...
> (8454, 119654)
> Traceback (most recent call last):
>   File "/workspaces/testATAC_scBioinf_Docker/scripts/Python_scripts/run_scibd.py", line 39, in <module>
>     run_doublet_detection(args.input, args.output)
>   File "/workspaces/testATAC_scBioinf_Docker/scripts/Python_scripts/run_scibd.py", line 22, in run_doublet_detection
>     KNNITER = si.KNNIter(
>   File "/opt/python3.10/lib/python3.10/site-packages/scibd-0.1.3-py3.10.egg/scibd/scibd.py", line 624, in __init__
>     self.jac = CalJac(self.rawmat)
>   File "/opt/python3.10/lib/python3.10/site-packages/scibd-0.1.3-py3.10.egg/scibd/scibd.py", line 92, in CalJac
>     jac_distance = (1-intersect/union).A
>   File "/opt/python3.10/lib/python3.10/site-packages/scipy/sparse/_base.py", line 536, in __rsub__
>     raise NotImplementedError('subtracting a sparse array from a '
> NotImplementedError: subtracting a sparse array from a nonzero scalar is not supported

Looking at the `scIBD/scibd/scibd.py` and checking on the `CalJac` function I see that `CalJac` keeps data in sparse format for some time before conversion:
```
def CalJac(A,B=None):##scipy mat
    A = A.astype(bool).astype(int)
    if B is None:
        B = A
    else:
        B = B.astype(bool).astype(int)
    intersect = A.dot(B.T)
    a_sum = A.sum(axis=1).A1
    b_sum = B.sum(axis=1).A1
    xx,yy = np.meshgrid(a_sum, b_sum)
    union = ((xx+yy).T - intersect)
    jac_distance = (1-intersect/union).A
    return jac_distance
```

I`ve tried converting the data to dense matrix early on in the function 
```
def CalJac(A,B=None):##scipy mat
    A = A.astype(bool).astype(int)
    if B is None:
        B = A
    else:
        B = B.astype(bool).astype(int)

    # Convert to dense matrix before dot product
    intersect = np.array(A.dot(B.T).todense())

    # Calculate sums
    a_sum = A.sum(axis=1)
    b_sum = B.sum(axis=1)

    xx,yy = np.meshgrid(a_sum, b_sum)
    union = ((xx+yy).T - intersect)

    # Calculate Jackard distance with the dense arrays
    jac_distance = 1-intersect/union
    return jac_distance
```

And now everything worked smoothly

> Reading input file...
> Input matrix shape: (8454, 215955)
> Matrix type: <class 'scipy.sparse._csr.csr_matrix'>
> Converting to dense matrix...
> Matrix converted to dense format
> New matrix type: <class 'numpy.ndarray'>
> Matrix values range: 0.0 - 1.0
> Initializing KNNIter...
> (8454, 82161)
> evaluating the input data!
> PCA
> Evaluate time:  297.09861850738525
> Running IterCall...
> Iteration 1 start
> Iteration 2 start
> Iteration 3 start
> Iteration 4 start
> Iteration 5 start
> Iteration 6 start
> Done
> ALL time: 1264.73455452919
> Saving results...
> Done!

I\`m not good at Python, but the solution worked and I got my desired results. I`m not sure if my solution is good in terms of memory efficiency or anything, but maybe it is something worth looking into. Thank you again for your tool! Testing it on my data further 

**System info**
Python version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
NumPy version: 2.0.2
SciPy version: 1.14.1
AnnData version: 0.11.1

**Comment by Ying-Lab** [comment]
Hi!
  Thank you for your interest and providing the valuable suggestions. I assessed my own codes, in CalJAC function, the sparse matrix is to improve the calculation of Jaccard similarity, and indense matrix is quite suffers from the memory efficiency and calculation. 
  I found that you converted the sparse matrix into dense matrix before feeding into KNNIter Class. I suggest that you can retain the sparse type during the iteration. Please have a try to see whether it works.
  
Best regards,
Scotty Zhang
